import { useTheme } from '@/hooks/use-theme';
import { StyleSheet } from 'react-native';

type Theme = ReturnType<typeof useTheme>;

export const makeDashboardStyles = (theme: Theme) => StyleSheet.create({
  wrapper: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    backgroundColor: theme.background,
    paddingTop: 40,
    paddingBottom: 40,
    gap: 30,
  },
  listContent: {
    gap: 20,
    maxHeight: 350
  },
  container: {
    backgroundColor: theme.primaryDark,
    width: '95%',
    minHeight: 310,
    borderRadius: 30,
    padding: 25,
    gap: 50,
  },
  containersRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: "space-between", 
    alignItems: "center",
    gap: 20,
  },
  chartContainersRow: {
    width: '100%',
    minHeight: 500,
    flexDirection: 'row',
    gap: 20,
  },
  pieChartContentRow: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    paddingTop: 30,
  },
  chartLegendContainer: {
    width: '60%',
    maxWidth: '100%',
    minHeight: 240,
    height: '70%',
    backgroundColor: theme.background,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: theme.border,
    gap: 24,
    padding: 20,
  },
  chartLegendLabel: {
    flexDirection: 'row',
    gap: 20,
    width: '100%',
    minHeight: 38,
  },
  chartLegendColorBox: {
    width: 10,
    height: 10,
    borderRadius: 30,
  },

  dashboardSectionsRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
    paddingBottom: 10
  },
  dashboardSectionsColumn: {
    width: '95%',
    flexDirection: 'column',
    gap: 20,
  },
  containersColumn: {
    width: '95%',
    flexDirection: 'column',
    gap: 10,
  },
  containerBadge: {
    width: 80,
    height: 30,
    borderRadius: 30,
    backgroundColor: theme.surfaceSoft,
    justifyContent: 'center',
    alignItems: 'center',
  },
  transactionCard: {
    backgroundColor: theme.background,
    justifyContent: 'center',
    width: '100%',
    minHeight: 72,
    borderRadius: 10,
    padding: 10,
  },
  containersText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.text,
  },
  goalContainer: {
    overflow: 'hidden',
    backgroundColor: theme.surface,
    flex: 1,
    height: '60%',
    borderRadius: 30,
    padding: 20,
    paddingRight: 0,
    gap: 10,
    borderWidth: 1,
    borderColor: theme.border,
  },
  goalList: {
    flex: 1,
  },
  goalPercentage: {
    marginRight: -20,
    marginLeft: 'auto',
    alignItems: 'center',
    justifyContent: 'center',
    width: 45,
    height: 24,
    borderRadius: 30,
    backgroundColor: theme.primaryMuted,
  },
  percentageText: {
    fontSize: 13,
    color: '#FFF',
    fontWeight: 'bold',
    alignContent: 'center',
  },
  emptyProgressBar: {
    height: 8,
    borderRadius: 4,
    backgroundColor: theme.primarySoft,
    overflow: 'hidden',
  },
  fillProgressBar: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: theme.primaryMuted,
  },
  innerCollumn: {
    borderRadius: 8,
  },
  cardsRow: {
    flexDirection: 'row',
    marginTop: 'auto',
    gap: 16,
  },
  card: {
    flex: 1,
    backgroundColor: theme.primarySoft,
    borderRadius: 16,
    padding: 16,
    minHeight: 96,
  },
  cardLabel: {
    fontSize: 16,
    color: theme.primary,
  },
  cardBalance: {
    fontSize: 22,
    color: theme.text,
    fontWeight: 'bold',
  },
  title: {
    fontSize: 30,
    fontWeight: 'bold',
    color: theme.text,
  },
  subtitle: {
    fontSize: 14,
    color: theme.primary,
    fontWeight: 'bold',
  },
  balancetext: {
    fontSize: 55,
    fontWeight: 'bold',
    marginTop: -10,
    color: theme.text,
  },
  descriptionText: {
    marginTop: -5,
    fontSize: 16,
    color: theme.textSecondary,
  },
  iconContainer: {
    width : 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: theme.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconTextGroup: {
  flexDirection: 'row',
  alignItems: 'center',
  gap: 10,
  flex: 1,
  },
  movementsContainer: {
    overflow: 'hidden',
    backgroundColor: theme.surface,
    flex: 2,
    height: '60%',
    borderRadius: 30,
    padding: 20,
    gap: 5,
    borderWidth: 1,
    borderColor: theme.border,
  },
  chartContainer: {
    overflow: 'hidden',
    backgroundColor: theme.surface,
    flex: 1,
    minWidth: 0,
    minHeight: 500,
    borderRadius: 30,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.border,
  },
  dashboardSectionContainer: {
    overflow: 'hidden',
    backgroundColor: theme.surface,
    flex: 1,
    minHeight: 500,
    borderRadius: 30,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.border,
  }
});
